
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: lab_postgres
    environment:
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpass
      POSTGRES_DB: labdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./Backend/init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - covid-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: lab_backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: labuser
      DB_PASSWORD: labpass
      DB_NAME: labdb
      FLASK_PORT: 5000
      FLASK_ENV: development
    ports:
      - "5001:5000"
    depends_on:
      - db
    networks:
      - covid-network
    volumes:
      - ./Backend:/app

volumes:
  db_data:

networks:
  covid-network:
    driver: bridge
