version: "3.8"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: lab_postgres
    environment:
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpass
      POSTGRES_DB: labdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./Backend/init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  db_data:
